// vue-child/src/components/Page.vue
<template>
  <div class="Page">
    <h3>Page {{ number }}</h3>
  </div>
</template>

<script>

import {useRoute} from 'vue-router';
import {computed} from 'vue';

export default {
  name: "Page1",
  setup(props) {
    const route = useRoute();

    const number = computed(() => route.params.number);

    return {
      number
    };
  }
}
</script>

<style scoped>
  .Page > h3 {
    color: orange;
  }
</style>

// react-child/src/components/Page.js
import React from 'react';
import classes from './Page.css';
import {useRouteMatch} from 'react-router';

const Page = () => {
    const { params: { number } } = useRouteMatch();
    return (
        <div className={ classes.Page }>
            <h3>Page { number }</h3>
        </div>
    )
};

export default Page;
